[ChatUpdate] Added SentChatMessage-History & Chat Tab-Completion
djoslin0/sm64ex-coop pull request #241
Opened 2023-09-21 22:05 UTC by iZePlayzYT

- Fixed a few bugs and bad code regarding "default commands"
- Added SentChatMessages-History (including navigation)
- Added Tab-Completion for Main-Commands
- Added Tab-Completion for Sub-Commands
- Added Tab-Completion for Playernames (Not working correctly yet. Infos -> Check the comment at line 425 in the class "djui_chat_box.c" (Method: djui_chat_box_input_on_key_down, "case SCANCODE_TAB:")

2023-09-22 08:51 UTC, yoyeet961 commented
you should make this pull request on the dev branch of https://github.com/sm64ex-coop-dev/sm64ex-coop

2023-09-22 08:51 UTC, yoyeet961 commented
its a private repo tho so you should ping djoslin0 in the coop server asking to get access to it and your github username

2023-09-23 12:32 UTC, yoyeet961 commented
also why did you increase the hooked chat command limit to 8192? hooking so much chat commands might even crash the game

2023-09-23 12:34 UTC, yoyeet961 reviewed
when i tried using printf, the game always crashed, so consider not using printf.

2023-09-23 12:59 UTC, yoyeet961 requested changes
there are a lot of stuff in your code that needs to be modified/added

2023-09-23 12:59 UTC, yoyeet961 commented on src/pc/lua/smlua_hooks.c
> +#define MAX_HOOKED_CHAT_COMMANDS 8192
you should change this back to 64, what mod needs 8192 commands

2023-09-23 12:59 UTC, yoyeet961 commented on src/pc/djui/djui_chat_box.c
> +#define MAX_HISTORY_SIZE 1000
who will press arrow up 1000 times?

2023-09-23 12:59 UTC, yoyeet961 commented on src/pc/djui/djui_chat_box.c
> +    strncpy(sTabCompletionOriginalText, "", MAX_MSG_LENGTH - 1);
consider using snprintf instead of strncpy

2023-09-23 12:59 UTC, yoyeet961 commented on src/pc/djui/djui_chat_box.c
> +    free(players);
why are you doing free()? doesnt that deallocate the return value of smlua_get_chat_player_list()?

2023-09-23 12:59 UTC, yoyeet961 commented on src/pc/djui/djui_chat_box.c
>  #include "pc/lua/smlua_hooks.h"
you need to include djui_interactable.h or else there wont be any SCANCODE_ stuff

2023-09-23 13:34 UTC, iZePlayzYT commented on src/pc/djui/djui_chat_box.c
> +#define MAX_HISTORY_SIZE 1000
i decreased it to 256

2023-09-23 13:35 UTC, iZePlayzYT commented on src/pc/djui/djui_chat_box.c
> +    strncpy(sTabCompletionOriginalText, "", MAX_MSG_LENGTH - 1);
done

2023-09-23 13:35 UTC, iZePlayzYT commented on src/pc/djui/djui_chat_box.c
> +    free(players);
no, it does not

2023-09-23 13:35 UTC, iZePlayzYT commented on src/pc/djui/djui_chat_box.c
>  #include "pc/lua/smlua_hooks.h"
never touch a running system or code.

2023-09-23 13:36 UTC, iZePlayzYT commented on src/pc/lua/smlua_hooks.c
> +#define MAX_HOOKED_CHAT_COMMANDS 8192
i decreased it to 512

2023-09-23 13:36 UTC, iZePlayzYT commented
some changes done

2023-09-23 13:38 UTC, yoyeet961 commented
ok but you still didnt include djui_interactables.h

2023-09-23 18:20 UTC, yoyeet961 commented on src/pc/djui/djui_chat_box.c
>  #include "pc/lua/smlua_hooks.h"
what
if you don't include it then all the SCANCODE_ stuff will be NULL, and so all of it will pretty much be 0

2023-09-24 02:27 UTC, iZePlayzYT reviewed
test123

2023-09-24 02:49 UTC, closed without merging